
export const LOADING_PROJECTS = 'LOADING_PROJECTS'
export const ADD_PROJECT = 'ADD_PROJECT'
export const EDIT_PROJECT = 'EDIT_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const GET_PROJECTS = 'GET_PROJECTS'
export const PROJECT_FILTERS = 'PROJECT_FILTERS'
export const PROJECT_FILTERS_RESET = 'PROJECT_FILTERS_RESET'
export const PROJECT_SORT = 'PROJECT_SORT'
export const PROJECT_ORDER = 'PROJECT_ORDER'
export const PROJECT_PAGINATION = 'PROJECT_PAGINATION'


export * from './projectActions'
